<?xml version="1.0" encoding="utf-8"?>
<kenticocommunity.qandaanswerdata>
  <QAndAAnswerDataAuthorMemberID>
    <GUID>8fb0dad6-8c28-43e4-849b-684df65417a7</GUID>
    <ObjectType>cms.member</ObjectType>
  </QAndAAnswerDataAuthorMemberID>
  <QAndAAnswerDataCodeName>-we-upgraded-from-version-29-1-0-we-upgrad5b22cde9</QAndAAnswerDataCodeName>
  <QAndAAnswerDataContent><![CDATA[
- we upgraded from version 29.1.0
- we upgraded all the projects
- we did not have any custom integrations
- we didn't have any custom middleware

We reverted the database and tried the upgrade again and it's working now. We may have not run the CI correctly. That's my best guess, anyhow!
]]></QAndAAnswerDataContent>
  <QAndAAnswerDataDateCreated>2024-09-27 17:36:00Z</QAndAAnswerDataDateCreated>
  <QAndAAnswerDataGUID>4fc35537-37be-4420-81fe-dd0bcee9d2db</QAndAAnswerDataGUID>
  <QAndAAnswerDataQuestionWebPageItemID>
    <CodeName>Error-after-upgrading-to-29-4-1-f7eafc8b-toxsbg56</CodeName>
    <GUID>c4d143d7-88df-4513-89f1-1ca8c5e2bc1e</GUID>
    <ObjectType>cms.webpageitem</ObjectType>
  </QAndAAnswerDataQuestionWebPageItemID>
  <QAndAAnswerDataWebsiteChannelID>
    <GUID>9ca57e0f-969f-43be-91d3-6c45659316bd</GUID>
    <ObjectType>cms.websitechannel</ObjectType>
    <Parent>
      <CodeName>devnet</CodeName>
      <GUID>4f636110-fd4a-4905-83e6-998752c2b2c2</GUID>
      <ObjectType>cms.channel</ObjectType>
    </Parent>
  </QAndAAnswerDataWebsiteChannelID>
</kenticocommunity.qandaanswerdata>