<?xml version="1.0" encoding="utf-8"?>
<kenticocommunity.qandaanswerdata>
  <QAndAAnswerDataAuthorMemberID>
    <GUID>f69d9d84-4ca9-4a3d-80f0-cff18438940a</GUID>
    <ObjectType>cms.member</ObjectType>
  </QAndAAnswerDataAuthorMemberID>
  <QAndAAnswerDataCodeName>Our-developers-are-already-looking-into-th2a9321a2</QAndAAnswerDataCodeName>
  <QAndAAnswerDataContent>
    <![CDATA[Our developers are already looking into this issue - multiple customers are having this issue as well. At this moment it seems that the devs identified the source of the issue and are currently working on a fix. Hopefully it will be available this week!&#x20;]]>
  </QAndAAnswerDataContent>
  <QAndAAnswerDataDateCreated>2025-09-01 16:41:33Z</QAndAAnswerDataDateCreated>
  <QAndAAnswerDataGUID>548351aa-8eed-4fc4-9a08-249773b5ae68</QAndAAnswerDataGUID>
  <QAndAAnswerDataQuestionWebPageItemID>
    <CodeName>Getting-exception-after-upgrading-to-30-9-1-a8037911-wkph1uu7</CodeName>
    <GUID>074231a9-7fc8-4522-a91e-af5039389255</GUID>
    <ObjectType>cms.webpageitem</ObjectType>
  </QAndAAnswerDataQuestionWebPageItemID>
  <QAndAAnswerDataWebsiteChannelID>
    <GUID>9ca57e0f-969f-43be-91d3-6c45659316bd</GUID>
    <ObjectType>cms.websitechannel</ObjectType>
    <Parent>
      <CodeName>devnet</CodeName>
      <GUID>4f636110-fd4a-4905-83e6-998752c2b2c2</GUID>
      <ObjectType>cms.channel</ObjectType>
    </Parent>
  </QAndAAnswerDataWebsiteChannelID>
</kenticocommunity.qandaanswerdata>